// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// set_bgen
List set_bgen(SEXP bgenfile_in);
RcppExport SEXP _bgenR_set_bgen(SEXP bgenfile_in) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(set_bgen(bgenfile_in));
    return rcpp_result_gen;
END_RCPP
}

// query_bgen
List query_bgen();
RcppExport SEXP _bgenR_query_bgen() {
    BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(query_bgen());
    return rcpp_result_gen;
    END_RCPP
}

// close_bgen
List close_bgen();
RcppExport SEXP _bgenR_close_bgen() {
    BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(close_bgen());
    return rcpp_result_gen;
    END_RCPP
}


static const R_CallMethodDef CallEntries[] = {
    {"_bgenR_set_bgen", (DL_FUNC) &_bgenR_set_bgen, 1},
    {"_bgenR_query_bgen", (DL_FUNC) &_bgenR_query_bgen, 0},
    {"_bgenR_close_bgen", (DL_FUNC) &_bgenR_close_bgen, 0},  
    {NULL, NULL, 0}
};

RcppExport void R_init_test(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
